add effect "looper" - kind of like bounce, but w/o the bouncing. you …
jdblair/MegaPrayer-oscled pull request #28
Opened 2017-06-14 20:32 UTC by jdblair

…can set the length of the train of beads and the "speed" as a signed float. the sign is the direction, and the speed can be non-integer. also it really looks best on the 'ring' bead_set

try this:
r.add_effect(name='looper', length='5', speed=.5, bead_set='ring')

i've updated bounce to work the same way

2017-06-15 07:36 UTC, GANDAMU requested changes
This all looks good, but it seems you're missing looper.py?

2017-06-15 07:50 UTC, jdblair commented
added!

2017-06-17 03:51 UTC, KellyOgilvie approved these changes

2017-06-18 10:32 UTC, jdblair commented
I added looper.py, I'm merging this to clean up.

2017-06-18 10:32 UTC, merged