Jdb the great expansion
jdblair/MegaPrayer-oscled pull request #32
Opened 2017-06-23 15:25 UTC by jdblair

This changes the format of the OSC message so we can send 1 message and update a whole set of beads at once. This appears to fix our performance problems caused by trying to update 480 beads (the individual LEDs on the cross) b/c now they can be sent as 1 update.

Beads now have a "class" value that defines the name of the set. Currently there is rosary, cross and bases. The new format is /bead siib <class> <base> <count> <binary blob>. The base is the starting bead number. The count is the number of beads. The binary blob has 4 bytes per bead in the form r,g,b,brightness.

2017-06-23 15:26 UTC, jdblair commented on python/mp/color.py
> +        self.brightness = 0xff;  # brightness used by APA102 LED module
We're not using this yet, but the APA102 LED module has a 4th value that can be used to control the overall brightness level by controlling the current flowing to all three LEDs

2017-06-23 15:26 UTC, jdblair commented on python/mp/rosary.py
> +        self.index = int(index)
this was an early experiment to speed things up, b/c I read that python3 iterators are slower if you don't force values to int().

2017-06-23 15:27 UTC, jdblair commented on python/mp/rosary.py
> +
This object contains the context needed to send an OSC message for a set of beads. This context is name (class), the bead_list for the set of beads, and the osc_client object.

2017-06-23 15:28 UTC, jdblair commented on python/mp/rosary.py
> +        self.cross = []
This is the 2 new sets of beads: bases and cross.

2017-06-23 15:28 UTC, jdblair commented on python/mp/rosary.py
>          self.run_mainloop = False
size of two new set of beads

2017-06-23 15:29 UTC, jdblair commented on python/mp/rosary.py
this holds the list of Updater objects that we step through in our mainloop

2017-06-23 15:30 UTC, jdblair commented on python/mp/rosary.py
create the three sets of beads and the associated Updater

2017-06-23 15:30 UTC, jdblair commented on python/mp/rosary.py
>          }
two new set names: base and cross. we're going to want more, but this gets us started.

2017-06-23 15:32 UTC, jdblair commented on python/mp/rosary.py
>              bead.color.set(self.bgcolor)
reset all the beads in all the bead classes

2017-06-23 15:37 UTC, jdblair commented on python/mp/rosary.py
> +            ))
This is where we pack the binary blob format: r,g,b,brightness in 4 binary bytes. The byte order is big endian (network byte order) b/c that's the tradition, even though it means byte-swapping on both ends of the wire.

2017-06-23 15:40 UTC, jdblair commented on python/pympsim/simulator.py
> +
I left this in here in case we need it again, even though its cruft.

2017-06-23 15:41 UTC, jdblair commented on python/pympsim/simulator.py
Decode the binary blob

2017-06-23 15:41 UTC, jdblair commented on python/pympsim/OSCserver.py
>      beadblob = []
push the binary blob on the queue

2017-06-23 15:42 UTC, jdblair commented on src/opi/PlatformSerialFactory.cpp
These are the GPIO locations in the new interface board.
See https://oshpark.com/orders/9GaWwwGm

2017-06-23 15:43 UTC, jdblair commented on src/oscled.json
>                  }
this is an example "base" class. all controllers will have at least one base attached on the third port.

2017-06-23 15:43 UTC, jdblair commented on src/OSCServer.h
>      int bind(std::shared_ptr<IPlatformSerial> const ser, OSCLedConfig::interface_config const &cfg);
whoops, i didn't end up using these.

2017-06-24 20:45 UTC, GANDAMU requested changes
It all LOOKs good, for the most part, save for my point about the beads. But I can't manage to add any effects.

I'm hoping my one point had something to do with it though.

2017-06-24 20:45 UTC, GANDAMU commented on python/mp/rosary.py
> +        self.osc_client.send(msg.build())
If I understand the point of this PR correctly, it's now the job of the Updater classes to call update() and set the colors on the individual beads? What do the changes here do then? Or rather, what does rosary.update() do now?

2017-06-24 20:45 UTC, GANDAMU commented on python/mp/rosary.py
> +            ))
If I understand correctly, we used to send /beadf with a bead ID and a color, and now we're sending /bead with a bead ID start, how many beads from there, and the color?

2017-06-24 20:45 UTC, GANDAMU commented on python/mp/rosary.py
> +
Shouldn't the bead class be taking a name arg too now? Unless I'm missing something, just reading this it seems self.bases[0], self.beads[0], and self.cross[0] would all refer to the same bead?

2017-06-25 15:09 UTC, jdblair commented on python/mp/rosary.py
> +            ))
We're sending the starting bead, the number of beads and then a binary blob that contains the colors for all of those beads. It means we send 3 updates for all the "beads": 1 for the original rosary beads, 1 for the lights in the 9 base structures, and 1 for the 480 LEDs in the cross. It was too expensive to send 60 + 9 + 480 individual updates.

2017-06-25 15:20 UTC, jdblair commented on python/mp/rosary.py
> +
No, Bead should not take a name. self.bases[0], self.beads[0] and self.cross[0] do not refer to the same bead. There are 3 python lists of beads to help us keep them straight, but the effects never see these arrays. The effects get sets of beads, and we can pull those sets from any of the three sets of beads.

Right now if you mix beads from multiple lists in the same set we have a problem b/c they won't sort correctly. I'm "sorting" that out still. Hah. In reality I don't think we will want to combine, say, the cross and the rosary in the same effect so I'm not too concerned.

2017-06-25 15:22 UTC, jdblair commented on python/mp/rosary.py
> +        self.osc_client.send(msg.build())
rosary.update() is cruft now. I should have removed it. Or we can keep it and I can move the code that calls updater there.

2017-06-25 15:29 UTC, jdblair commented on python/mp/rosary.py
> +
To put it another way, here are some examples:

# run 3phase_sine_wave on the cross
oscsend localhost 5006 /rosary/add_effect/name/3phase_sine_wave/bead_set/cross
# run throb on the bases
oscsend localhost 5006 /rosary/add_effect/name/throb/bead_set/bases
# run bounce on the rosary
oscsend localhost 5006 /rosary/add_effect/name/bounce/bead_set/rosary

2017-06-25 19:02 UTC, merged