- Low power mode via trigger
jdblair/MegaPrayer-oscled pull request #48
Opened 2017-08-13 06:22 UTC by GANDAMU

Copy/pasted from code comments:
```
    To go into low power mode:

        oscsend localhost 5006 /trigger/low_power_mode i 1

    To go into normal power mode:

        oscsend localhost 5006 /trigger/low_power_mode i 0
```

Backup gets saved in same directory that rosary.py resides in, e.g. `MegaPrayer-oscled/python/mp/low_power_mode.json`

2017-08-13 06:25 UTC, GANDAMU commented on python/mp/rosary.py
> +        self.osc_client.send(msg.build())
@jdblair You're probably gonna wanna check this part.

2017-08-15 14:55 UTC, jdblair requested changes
Looks good, except for writing the state every 10 seconds.

2017-08-15 14:55 UTC, jdblair commented on python/mp/rosary.py
> +
Please move this into the trigger handler so its only written once per state change. I don't want to wear out the flash memory faster than necessary.

2017-08-15 14:55 UTC, jdblair commented on python/mp/triggers/low_power_mode.py
> +        self.rosary.low_power_mode = self.low_power_mode
Can we call `self.rosary.write_to_disk()` here?

2017-08-16 06:13 UTC, GANDAMU reviewed
Yeah, I really was just doing it every 10 seconds to be safe. Did play with the idea of only writing on triggers, but figured it wouldn't hurt to just write a bit more. Turns out, it would.

Tested locally by just firing the trigger and checking the file. Still not sure if the OSC message is correct, but if you're good I'm good.

2017-08-16 06:13 UTC, GANDAMU commented on python/mp/triggers/low_power_mode.py
> +        self.rosary.power_mode_updater.write_to_disk()
Alright, writing from here now.

2017-08-16 06:13 UTC, GANDAMU commented on python/mp/rosary.py
> +            self.power_mode_updater.update()
Just updating using whatever power_mode_updater's own low_power_mode value is.

2017-08-16 16:16 UTC, jdblair commented on python/mp/triggers/low_power_mode.py
> +        self.rosary.power_mode_updater.write_to_disk()
thanks

2017-08-17 08:12 UTC, GANDAMU commented
Okay, @jdblair I *think* that's what you mean when you say "remove them." If I'm misinterpreting, you can just go ahead and fix that. I'm not like super possessive about this branch or anything.

2017-08-19 17:30 UTC, merged